# Clusterung von Bildern mit dem K-Means-Algorithmus
## Wichtig: hier müssen die Clusterpunkte als Integer definiert sein
 

Quelle:[Lehrtext der ETH-Zürich](http://www.educ.ethz.ch/unterrichtsmaterialien/mathematik/k-means-algorithmus.html)
Hier ein Beispiel:

<table><tr><td><img src='cover_kl.png'></td><td><img src='cover_ausgabe_kl.png'></td></tr>
<tr><td>Ausgangsbild</td><td>Bild komprimiert mit nur 5 Farben</td></tr>
</table>




In [1]:
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import numpy as np
import random
class k_Means():
    """
        Erhaelt eine Punkt-Liste als Array
        die Anzahl der Clusterpunkte
        eventuell die Cluster-Liste, wenn nicht,
        werden die Cluster-Punkte zufaellig aus den
        Punkten der PL bestimmt
    """
    def __init__(self, punkte, anzahl, clLi=None):        
        #print(self.clLi)
        self.puLi = punkte
        self.anzahlCluster = anzahl
        self.laengePuLi, self.dimPunkte =self.puLi.shape
        if clLi:
            self.clLi=clLi
        else:
            self.bestimmeCL()
        print("StartCluster: \n", self.clLi)
        self.cluster= np.zeros((self.laengePuLi,),dtype=int)
        self.error=20
        self.cls=[]
        
    def bestimmeCL(self):
        #zufaellige Auswahl der Clusterpunkte aus den gegebenen
        # MUESSEN INTEGER SEIN
        self.clLi=np.zeros((self.anzahlCluster,self.dimPunkte),dtype=int)
        clListe=[]
        i=0
        while len(clListe) < self.anzahlCluster:
            index= random.randint(0,self.laengePuLi-1)
            cl=self.puLi[index]
            if not self.istEnthalten(clListe,cl): #vermeide Doppelte
                clListe.append(cl)
                self.clLi[i]=self.puLi[index]
                i+=1
                
    def istEnthalten(self,array,el):
        for e in array:
            if (e==el).all():
                return True
        return False
        
    def einteilRunde(self):        
        for i in range(self.laengePuLi):
            #print("Abstaende: ",self.clLi,self.puLi[i])
            abstand=np.linalg.norm(self.clLi-self.puLi[i],axis=1)
            #print(abstand)
            cluster = np.argmin(abstand)
            #print(cluster)
            self.cluster[i]=cluster        
        self.clLi_old=np.copy(self.clLi)
        self.cls.append(self.clLi_old)
        for i in range(self.anzahlCluster):            
            punkte= [self.puLi[j] for j in range(self.laengePuLi) if self.cluster[j]==i]                 
            self.clLi[i]=np.mean(punkte,axis =0)
        print("Neue Cluster: \n", self.clLi)
        self.error = np.linalg.norm(self.clLi-self.clLi_old)
        print(self.error)
        
    def einteilen(self,bis=0):           
        self.einteilRunde()
        while self.error> bis:            
            self.einteilRunde()            
            self.gibZahlen()
            
    def gibZahlen(self):
        print("Verteilung der Punkte auf die Cluster")
        #liefert die Anzahlen der Punkte je Cluster
        for i in range(self.anzahlCluster):            
            punkte= [self.puLi[j] for j in range(self.laengePuLi) if self.cluster[j]==i]
            print(i,len(punkte))
        
    def zeigen(self):
        fig = plt.figure()
        fig.suptitle("Einteilung in Cluster")
        ax = fig.add_subplot(111)        
        farben=["red","yellow","blue","green","lightblue","grey"]*2
        m=["+","x","*","o","v"]*20
        for i in range(self.anzahlCluster):
            xs= [self.puLi[j][0] for j in range(self.laengePuLi) if self.cluster[j]==i]
            ys= [self.puLi[j][1] for j in range(self.laengePuLi) if self.cluster[j]==i]
            #print("xs: ",xs," ys: ",ys)            
            ax.scatter(xs,ys, c=farben[i])        
        si=-1#Markerzaehler
        for c in self.cls:            
            si+=1
            for i in range(self.anzahlCluster):
                ax.scatter(c[i][0],c[i][1], c="black",marker=m[si])                      
        #for c in self.clLi:
            #ax.scatter(c[0],c[1], c="black",marker=m[0])
        maxis=np.amax(self.puLi,0)
        minis=np.amin(self.puLi,0)
        print("Maxis ",maxis, " Minis: ",minis)
        plt.axis([int(minis[0])-1,int(maxis[0])+1,
                  int(minis[1])-1,int(maxis[1])+1])
        plt.show()

In [2]:
class BildKMeans:
    def __init__(self,datei,anz):
        """
        bekommt den Dateinamen des Bildes und die Anzahl der Farben
        """
        self.datei=datei
        self.anz=anz
        
    def clustern(self,bis=0):
        #wie groß darf die Abweichung sein, default=0
        bk.ppm2array()
        self.k=k_Means(bk.piArray,self.anz)
        self.k.einteilen(bis)        

    def ppm2array(self):
        #einlesen und Array erstellen
        f = open (datei,"r")
        inhalt= f.readlines()
        self.kopf=inhalt[:4]
        groesse=self.kopf[2].strip().split()
        
        self.hoehe=int(groesse[1])
        self.breite=int(groesse[0])
        print(groesse, self.breite, self.hoehe)
        bild=inhalt[4:]
        bli=[]
        for z in bild:
            pl = z.strip().split(" ")
            bli+=pl
        pili=[]
        for i  in range(0,len( bli),3):
            r= int(bli[i])
            g= int(bli[i+1])
            b= int(bli[i+2])
            pili.append([r,g,b])
        self.piArray=np.array(pili) #Startwerte des Bildes speichern
        #print(self.piArray, self.piArray.shape)
        #print(self.kopf)
        
    def array2ppm(self):
        #schreibe zurueck in Datei mit richtigem Format
        kopf=''
        for k in self.kopf:
            kopf+=k
        kopf=kopf[:-1]
        print(kopf)
        ausgabe=self.datei[:-4]+"_ausgabe.ppm"
        bAr=np.copy(self.k.puLi)        
        for i in range(self.k.laengePuLi):
            bAr[i]=self.k.clLi[self.k.cluster[i]]
        bAr=bAr.reshape(self.breite*3,self.hoehe)
        #bAr=np.array2string(bAr)
        print(bAr,bAr.shape)
        np.savetxt(ausgabe, bAr, fmt="%d" ,
                   delimiter=" ",header=kopf,
                   comments='')
        
        

In [3]:
datei="cover.ppm"
bk=BildKMeans(datei,5)
bk.clustern(10)
bk.array2ppm()

['600', '600'] 600 600
StartCluster: 
 [[  4  91 206]
 [  5  20 123]
 [108   9  29]
 [246   0 169]
 [  5  48 187]]
Neue Cluster: 
 [[ 53 168 164]
 [ 10  31  91]
 [114  50  24]
 [231  18 111]
 [  7  36 197]]
131.0228987620103
Neue Cluster: 
 [[ 93 225 125]
 [ 10  23  39]
 [159  82  24]
 [223  20  87]
 [  6  56 198]]
115.03477735015616
Verteilung der Punkte auf die Cluster
0 46869
1 83836
2 66893
3 63682
4 98720
Neue Cluster: 
 [[ 97 229 121]
 [ 18  22  28]
 [187 108  25]
 [218  12  85]
 [  6  55 193]]
42.59107887809371
Verteilung der Punkte auf die Cluster
0 45952
1 88784
2 51176
3 65173
4 108915
Neue Cluster: 
 [[ 95 228 122]
 [ 24  22  26]
 [211 144  28]
 [209   7  78]
 [  6  54 191]]
45.68369512200168
Verteilung der Punkte auf die Cluster
0 45426
1 92001
2 40377
3 70954
4 111242
Neue Cluster: 
 [[ 95 228 122]
 [ 24  22  25]
 [224 164  23]
 [204  12  76]
 [  6  54 191]]
25.475478405713993
Verteilung der Punkte auf die Cluster
0 45512
1 91877
2 32476
3 78404
4 111731
Neue Cluster: 
 [[