# Übung Vektoroperationen und Matrizenmultiplikation

Mit der Bibliothek numpy und den darin verfügbaren numpy-Arrays kann man die Operationen mit Vektoren und Matrizen einfach und übersichtlich darstellen. Dazu muss man eine Python-Liste in ein Array umwandeln. Eine eindimensionale Liste wird zu einem Vektor, eine zweidimensionale Liste zu einer Matrix.   
Siehe auch https://www.python-kurs.eu/matrix_arithmetik.php
## 1. Vektoroperationen:


In [3]:
import numpy
v1=numpy.array([1,2,3])
v2=numpy.array([0,3,2])
print("v1+v2:\n",v1+v2)
print("v1-v2:\n",v1-v2)
print("v1*v2:\n",v1*v2)
print(numpy.dot(v1,v2))   #Skalarprodukt
print(numpy.dot(v2,v1))
print(numpy.cross(v1,v2)) #Kreuzprodukt, nur für zwei- bzw. dreidimensionale Vektoren
print(numpy.cross(v2,v1))

v1+v2:
 [1 5 5]
v1-v2:
 [ 1 -1  1]
v1*v2:
 [0 6 6]
12
12
[-5 -2  3]
[ 5  2 -3]


## 2. Matrixoperationen
Die Regel ist immer die gleiche: 
Man definiert eine Matrix, indem man alle Elemente einer Zeile als Liste, die Listen zeilenweise als Liste von Listen definiert.   
Quelle: https://de.wikipedia.org/wiki/Matrizenmultiplikation  
Gegeben seien die beiden reellen Matrizen 

<math>A = \begin{pmatrix} 3 & 2 & 1 \\ 1 & 0 & 2 \end{pmatrix}
    <math>B = \begin{pmatrix} 1 & 2 \\ 0 & 1 \\ 4 & 0 \end{pmatrix}</math>  
Da die Matrix <math>A</math> ebenso viele Spalten wie die Matrix <math>B</math> Zeilen besitzt, ist die Matrizenmultiplikation <math>A * B</math> durchführbar. Nachdem <math>A</math> zwei Zeilen und <math>B</math> zwei Spalten hat, wird das Matrizenprodukt ebenfalls zwei Zeilen und Spalten aufweisen. Zur Berechnung des ersten Matrixelements der Ergebnismatrix werden die Produkte der entsprechenden Einträge der ersten Zeile von <math>A</math> und der ersten Spalte von <math>B</math> aufsummiert (die Sternchen stehen für noch nicht berechnete Elemente):
$$\begin{pmatrix} 3 &  2 &  1 \\ 1 & 0 & 2 \end{pmatrix} * \begin{pmatrix} 1 & 2 \\ 0 & 1 \\ \color{BrickRed} 4 & 0 \end{pmatrix}= \begin{pmatrix}  3 * 1 +  2 * 0 + 1 * 4  & \ast \\ \ast & \ast \end{pmatrix} = \begin{pmatrix} {\color{Blue} 7} & \ast \\ \ast & \ast \end{pmatrix}$$

### Das Ganze wird so programmiert:

In [2]:
import numpy                         # diese Bibliothek ist für die Funktionen zuständig
m1 = numpy.array([[1,-2,3,4]])        #eine Zeile, vier Spalte
m2 = numpy.array([[2],[3],[0],[-2]])  #vier Zeilen, eine Spalte
m3 = numpy.dot(m1,m2)                # dot ist die Funktion zur Matrizenmultiplikation
m4 = numpy.dot(m2,m1)
print("m1= \n",m1)
print("m2= \n",m2)
print("m3= dot(m1,m2)\n",m3)
print("m4= dot(m2,m1)\n",m4)
print("5+m4=\n",5+m4)
print("2*m4=\n",2*m4)
print("m2+m4=\n",m2+m4)
print("m1+m4=\n",m1+m4)
print("m2*m4=\n",m2*m4)
print("m1*m4=\n",m1*m4)

m1= 
 [[ 1 -2  3  4]]
m2= 
 [[ 2]
 [ 3]
 [ 0]
 [-2]]
m3= dot(m1,m2)
 [[-12]]
m4= dot(m2,m1)
 [[ 2 -4  6  8]
 [ 3 -6  9 12]
 [ 0  0  0  0]
 [-2  4 -6 -8]]
5+m4=
 [[ 7  1 11 13]
 [ 8 -1 14 17]
 [ 5  5  5  5]
 [ 3  9 -1 -3]]
2*m4=
 [[  4  -8  12  16]
 [  6 -12  18  24]
 [  0   0   0   0]
 [ -4   8 -12 -16]]
m2+m4=
 [[  4  -2   8  10]
 [  6  -3  12  15]
 [  0   0   0   0]
 [ -4   2  -8 -10]]
m1+m4=
 [[ 3 -6  9 12]
 [ 4 -8 12 16]
 [ 1 -2  3  4]
 [-1  2 -3 -4]]
m2*m4=
 [[  4  -8  12  16]
 [  9 -18  27  36]
 [  0   0   0   0]
 [  4  -8  12  16]]
m1*m4=
 [[  2   8  18  32]
 [  3  12  27  48]
 [  0   0   0   0]
 [ -2  -8 -18 -32]]


## 3. Die transponierte Matrix
https://de.wikipedia.org/wiki/Transponierte_Matrix  
Die transponierte Matrix, gespiegelte Matrix oder gestürzte Matrix ist in der Mathematik diejenige Matrix, die durch Vertauschen der Rollen von Zeilen und Spalten einer gegebenen Matrix entsteht. Die erste Zeile der transponierten Matrix entspricht der ersten Spalte der Ausgangsmatrix, die zweite Zeile der zweiten Spalte und so weiter. Anschaulich entsteht die transponierte Matrix durch Spiegelung der Ausgangsmatrix an ihrer Hauptdiagonale. Die Umwandlung einer Matrix in ihre transponierte Matrix wird Transponierung, Transposition oder Stürzen der Matrix genannt. 

In [1]:
import numpy as np
print("m4= \n",m4)
print("m4 transponiert \n",m4.T)
print("m1= \n",m1)
print("m1 transponiert \n",m1.T)
print("m1 *m1.T \n",np.dot (m1,m1.T))
print("m1 *m1.T \n",np.dot (m1.T,m1))

NameError: name 'm4' is not defined