# Neuronales Netz
Quelle: [BogoToBogo](https://www.bogotobogo.com/python/python_Neural_Networks_Backpropagation_for_XOR_using_one_hidden_layer.php), mit vielen Tutorials zu Python

Außerdem [hier](http://pandamatak.com/people/anand/771/html/node37.html) Erläuterungen zum Backpropagation-Algorithmus

In [4]:
import numpy as np
# die Aktivierungsfunktion und ihre erste Ableitung
def tanh(x):
    return np.tanh(x)
def tanh_abl(x):
    return 1.0-np.tanh(x)**2

Als Aktivierungsfunktion ist hier $f(x)= \tanh x =  \frac{sinh(x)}{cosh(x)}= \frac{e^x -e^{-x}}{e^x + e^{-x}}=1-\frac{2}{e^{2x}+1}$  gewählt, weil es die besten Lern-Ergebnisse  lieferte. Im Bild sieht man grün die Funktion und blau die Ableitungsfunktion $f'(x)= 1- f(x)² $. NACHRECHNEN! ![Aktivierungsfunktionen tanh](images/aktivierungsfunktionen.png)

Spezielles Netzwerk für XOR mit zwei Eingaben, einer Ausgabe und einer versteckten Schicht mit zwei Knoten: Layers = [2,2,1].
In der Quelle ist das Programm allgemeiner dargestellt, so dass es für andere Netze angewendet werden kann.
![Bild vom Netzwerk](images/NeuralNetworksDiagram00.png)


Die Korrektur der Gewichte mittels Backpropagation ist gut auf [Wikipedia](https://de.wikipedia.org/wiki/Backpropagation "Wikipedia") beschrieben


In [5]:
class NeuronalNetwork:
    def __init__(self):
        layers=[2,2,1]
        self.weights=[] #Gewichte zufaellig festlegen
        w=2*np.random.random((3,3))-1 #liegen zwischen -1 und 1
        self.weights.append(w)
        w=2*np.random.random((3,1))-1
        self.weights.append(w)
        self.fehler=0
        
    def prepareInput(self,inListe):
        # setzt eine Spalte mit Einsen als Bias vor die Eingabe
        eingabe=np.array(inListe)
        X        = np.ones((len(eingabe),len(eingabe[0])+1))
        X[:,1:] = eingabe
        print (X)
        return X
        
    def fit(self,X,y,lernrate=0.1,epoches=1000):
        for k in range(epoches):
            i=np.random.randint(X.shape[0])#zufaellig eine Eingabe waehlen
            a=[X[i]] # eine Liste der Ausgaben der einzelnen Schichten 
            for j in range(len(self.weights)):
                hidden_in  = np.dot(a[j],self.weights[j]) # Eingabe mal Gewichte
                hidden_out = tanh(hidden_in)              # Aktivierungsfunktion
                a.append(hidden_out)                      # anhaengen an die Liste
            error  = y[i]-a[-1]
            self.fehler +=np.sum(np.square(error))  #zur Kontrolle der quadr. Fehler   
            # Backpropagation, Fehler berechnen und an die Fehlerliste anhaengen
            deltas = [error * tanh_abl(a[-1])] #Fehler der Ausgabeschicht
            for j in range(len(a)-2,0,-1):
                deltas.append(deltas[-1].dot(self.weights[j].T)*tanh_abl(a[j]))
                # Fehleranteile der vorherigen Schichten
            deltas.reverse()            
            # Korrektur der Gewichte 
            for i in range(len(self.weights)):
                layer=np.array(a[i])
                layer=layer[:,None]#Umwandeln in eine nx1 Matrix 
                delta=np.array(deltas[i])
                delta=delta[None,:]#Umwandeln in eine 1xn-Matrix               
                self.weights[i]+=lernrate*np.dot(layer,delta)
          
    def predict(self,x):      
        for i in range(len(self.weights)):
            x=tanh(np.dot(x,self.weights[i]))            
        return x

In [6]:
#np.random.seed(0)#liefert reproduzierbare Ergebnisse

nn=NeuronalNetwork()
#Eingabevektor, die Vorbereitung erfolgt in einer Extra -Funktion des Netzes
eingabe=[[0, 0], [0, 1],[1, 0], [1, 1]]
#Die Ziel-Ausgabe
y = np.array([0, 1, 1, 0])
X=nn.prepareInput(eingabe)
#Test des Netzes
for i in range(20):
    print(i+1)
    nn.fit(X,y,0.1,100)
    for e in X:
        print(e[1:],nn.predict(e))
    print(nn.fehler)
    if nn.fehler<1:
        break
    nn.fehler=0
    print()

[[1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
1
[0. 0.] [0.40970512]
[0. 1.] [0.49440553]
[1. 0.] [0.42624589]
[1. 1.] [0.48831048]
29.013017180938164

2
[0. 0.] [0.47970861]
[0. 1.] [0.47115441]
[1. 0.] [0.56937753]
[1. 1.] [0.52778603]
25.588802294498926

3
[0. 0.] [0.53068935]
[0. 1.] [0.48239884]
[1. 0.] [0.61294021]
[1. 1.] [0.51054604]
24.83904746627341

4
[0. 0.] [0.58919265]
[0. 1.] [0.57285064]
[1. 0.] [0.64011024]
[1. 1.] [0.55024755]
23.038517410835734

5
[0. 0.] [0.5870239]
[0. 1.] [0.63867766]
[1. 0.] [0.68136016]
[1. 1.] [0.62660668]
22.44223015179765

6
[0. 0.] [0.32723775]
[0. 1.] [0.53407173]
[1. 0.] [0.47839322]
[1. 1.] [0.34448206]
22.102195181819052

7
[0. 0.] [0.2816829]
[0. 1.] [0.51486008]
[1. 0.] [0.66620405]
[1. 1.] [0.3697473]
16.633740824543633

8
[0. 0.] [0.06890852]
[0. 1.] [0.62359543]
[1. 0.] [0.58409192]
[1. 1.] [0.22817688]
12.289653323400914

9
[0. 0.] [0.18267473]
[0. 1.] [0.77169923]
[1. 0.] [0.65295537]
[1. 1.] [0.16939641]
7.873713315850853

10
