# Übung Vektoroperationen und Matrizenmultiplikation

Mit der Bibliothek numpy und den darin verfügbaren numpy-Arrays kann man die Operationen mit Vektoren und Matrizen einfach und übersichtlich darstellen. Dazu muss man eine Python-Liste in ein Array umwandeln. Eine eindimensionale Liste wird zu einem Vektor, eine zweidimensionale Liste zu einer Matrix.   
Siehe auch https://www.python-kurs.eu/matrix_arithmetik.php
## 1. Vektoroperationen:


In [9]:
import numpy
v1=numpy.array([1,2,3])
v2=numpy.array([0,3,2])
print("v1+v2:\n",v1+v2)
print("v1-v2:\n",v1-v2)
print("v1*v2:\n",v1*v2)
print(numpy.dot(v1,v2))   #Skalarprodukt
print(numpy.dot(v2,v1))
print(numpy.cross(v1,v2)) #Kreuzprodukt, nur für zwei- bzw. dreidimensionale Vektoren
print(numpy.cross(v2,v1))

v1+v2:
 [1 5 5]
v1-v2:
 [ 1 -1  1]
v1*v2:
 [0 6 6]
12
12
[-5 -2  3]
[ 5  2 -3]


## 2.Definition der Matrixelemente
In der Mathematik versteht man unter einer Matrix (Plural Matrizen) eine rechteckige Anordnung (Tabelle) von Elementen (meist mathematischer Objekte, etwa Zahlen). Mit diesen Objekten lässt sich dann in bestimmter Weise rechnen, indem man Matrizen addiert oder miteinander multipliziert.  
Quelle: https://de.wikipedia.org/wiki/Matrix_(Mathematik)  
In der Informatik fängt man anders als in Mathe bei Null an zu zählen.  
Video: https://www.youtube.com/watch?v=1sCwtISsyqc&feature=youtu.be&list=PLb0zKSynM2PBYzz6l37rWH3B_n_7P40QP in der gesamten Playlist werden alle Operationen ausführlich erklärt.

### Bezeichnungen

Eine Matrix $A_{mn}$ hat m Zeilen und n Spalten, die Bezeichnungen der einzelnen Elemente sieht man im Beispiel:  
$A = \begin{pmatrix} a_{00} & a_{01} & a_{02} \\ a_{10} & a_{11} & a_{12} \end{pmatrix}$



## 3. Matrixoperationen
Die Regel ist immer die gleiche: 
Man definiert eine Matrix, indem man alle Elemente einer Zeile als Liste, die Listen zeilenweise als Liste von Listen definiert.   
Quelle: https://de.wikipedia.org/wiki/Matrizenmultiplikation  
Gegeben seien die beiden reellen Matrizen  
$A = \begin{pmatrix} 3 & 2 & 1 \\ 1 & 0 & 2 \end{pmatrix}$ und 
    $B = \begin{pmatrix} 1 & 2 \\ 0 & 1 \\ 4 & 0 \end{pmatrix}$   
Da die Matrix <math>A</math> ebenso viele Spalten wie die Matrix <math>B</math> Zeilen besitzt, ist die Matrizenmultiplikation <math>A * B</math> durchführbar. Weil <math>A</math> zwei Zeilen und <math>B</math> zwei Spalten hat, wird das Matrizenprodukt ebenfalls zwei Zeilen und Spalten aufweisen. Zur Berechnung des ersten Matrixelements der Ergebnismatrix werden die Produkte der entsprechenden Einträge der ersten Zeile von <math>A</math> und der ersten Spalte von <math>B</math> aufsummiert (die Sternchen stehen für noch nicht berechnete Elemente):
$$\begin{pmatrix} 3 &  2 &  1 \\ 1 & 0 & 2 \end{pmatrix} \cdot \begin{pmatrix} 1 & 2 \\ 0 & 1 \\  4 & 0 \end{pmatrix} = \begin{pmatrix}  3 \cdot 1 +  2 \cdot 0 + 1 \cdot 4  & \ast \\ \ast & \ast \end{pmatrix} = \begin{pmatrix} 7 & \ast \\ \ast & \ast \end{pmatrix}$$

### Das Ganze wird so programmiert:

In [23]:
import numpy                         # diese Bibliothek ist für die Funktionen zuständig
m1 = numpy.array([[1,-2,3,4]])        #eine Zeile, vier Spalte
m2 = numpy.array([[2],[3],[0],[-2]])  #vier Zeilen, eine Spalte
m3 = numpy.dot(m1,m2)                # dot ist die Funktion zur Matrizenmultiplikation
m4 = numpy.dot(m2,m1)
print("m1= \n",m1)
print("m2= \n",m2)
print("m3= dot(m1,m2)\n",m3)
print("m4= dot(m2,m1)\n",m4)
print("5+m4=\n",5+m4)
print("2*m4=\n",2*m4)
print("m2+m4=\n",m2+m4)
print("m1+m4=\n",m1+m4)
print("m2*m4=\n",m2*m4)
print("m1*m4=\n",m1*m4)

m1= 
 [[ 1 -2  3  4]]
m2= 
 [[ 2]
 [ 3]
 [ 0]
 [-2]]
m3= dot(m1,m2)
 [[-12]]
m4= dot(m2,m1)
 [[ 2 -4  6  8]
 [ 3 -6  9 12]
 [ 0  0  0  0]
 [-2  4 -6 -8]]
5+m4=
 [[ 7  1 11 13]
 [ 8 -1 14 17]
 [ 5  5  5  5]
 [ 3  9 -1 -3]]
2*m4=
 [[  4  -8  12  16]
 [  6 -12  18  24]
 [  0   0   0   0]
 [ -4   8 -12 -16]]
m2+m4=
 [[  4  -2   8  10]
 [  6  -3  12  15]
 [  0   0   0   0]
 [ -4   2  -8 -10]]
m1+m4=
 [[ 3 -6  9 12]
 [ 4 -8 12 16]
 [ 1 -2  3  4]
 [-1  2 -3 -4]]
m2*m4=
 [[  4  -8  12  16]
 [  9 -18  27  36]
 [  0   0   0   0]
 [  4  -8  12  16]]
m1*m4=
 [[  2   8  18  32]
 [  3  12  27  48]
 [  0   0   0   0]
 [ -2  -8 -18 -32]]


## 5. Die transponierte Matrix
https://de.wikipedia.org/wiki/Transponierte_Matrix  
Die transponierte Matrix, gespiegelte Matrix oder gestürzte Matrix ist in der Mathematik diejenige Matrix, die durch Vertauschen der Rollen von Zeilen und Spalten einer gegebenen Matrix entsteht. Die erste Zeile der transponierten Matrix entspricht der ersten Spalte der Ausgangsmatrix, die zweite Zeile der zweiten Spalte und so weiter. Anschaulich entsteht die transponierte Matrix durch Spiegelung der Ausgangsmatrix an ihrer Hauptdiagonale. Die Umwandlung einer Matrix in ihre transponierte Matrix wird Transponierung, Transposition oder Stürzen der Matrix genannt. 

In [28]:
print("m4= \n",m4)
print("m4 transponiert \n",m4.T)
print("m1= \n",m1)
print("m1 transponiert \n",m1.T)

m4= 
 [[ 2 -4  6  8]
 [ 3 -6  9 12]
 [ 0  0  0  0]
 [-2  4 -6 -8]]
m4 transponiert 
 [[ 2  3  0 -2]
 [-4 -6  0  4]
 [ 6  9  0 -6]
 [ 8 12  0 -8]]
m1= 
 [[ 1 -2  3  4]]
m1 transponiert 
 [[ 1]
 [-2]
 [ 3]
 [ 4]]


## Berechnung der Abbildungsmatrix aus den Koordinaten von Original und Bild
Beispiel: Gegeben ist das Dreieck ABC die Punkte A(1|2), B(3|0) und C(2|2). Bestimmen Sie die Matrix für die Abbildung, die das Dreieck ABC auf das Dreieck A’B’C‘ mit den Punkten A‘(3|5), B‘(-1|1) und C‘(3|3) transformiert. Zeigen Sie, dass diese Transformation aus einer zentrischen Streckung am Ursprung und einer Drehung um E(-4|3) um 90° zusammengesetzt ist.
#### Ansatz
Die Transformation lässt sich durch die Multiplikation einer noch unbekannten Abildungsmatrix $M = \begin{pmatrix} m_{00} & m_{01} & m_{02} \\ m_{10} & m_{11} & m_{12}\\ m_{20} & m_{21} & m_{22} \end{pmatrix} $ mit den Punktvektoren darstellen, deren Ergebnis die Vektoren der Bildpunkte sind. Die Koordinaten der Punkte des Dreiecks ABC sind dabei die Spalten der zweiten Matrix, die letze Komponente ist wegen der homogenen Koordianten immer 1. Das Ergebnis ist eine Matrix, deren Spaltenvektoren die Koordinaten der Bildpunkte sind.
$$M = A \cdot A'$$
$$\begin{pmatrix} m_{00} & m_{01} & m_{02} \\ m_{10} & m_{11} & m_{12}\\ m_{20} & m_{21} & m_{22} \end{pmatrix} \cdot \begin{pmatrix} 1&3&2\\2&0&2\\1&1&1\end{pmatrix}= \begin{pmatrix} 3&-1&3\\5&1&3\\1&1&1\end{pmatrix}$$
Nun müssen die Komponenten der Matrix M berechnet werden. Die letzte Zeile ist klar, dort stehen wegen der homogenen Koordinaten stets die Zahlen 0, 0, 1.  
Die anderen Komponenten ergeben sich als Lösungen von linearen Gleichungssystemen, die sich durch die Regeln der Matrizenmultiplikation ergeben. Die Zahl 3 in der Ergebnismatrix ist das Produkt der ersten Zeile von M mit der ersten Spalte von A. Damit ergibt sich Gleichung I, die anderen beiden entsprechend:  

\begin{equation}
\rlap{\hspace{-2.4cm}(I)} 1\cdot m_{00} + 2 \cdot m_{01} + 1\cdot m_{02}=3 
\end{equation}
\begin{equation}
\rlap{\hspace{-2.5cm}(II)} 3\cdot m_{00} + 0 \cdot m_{01} + 1\cdot m_{02}=-1 
\end{equation}
\begin{equation}
\rlap{\hspace{-2.8cm}(III)} 2\cdot m_{00} + 2 \cdot m_{01} + 1\cdot m_{02}=3
\end{equation}
Die Lösung dieses Gleichungssystems ist dann die erste Zeile der Abbildungsmatrix, in diesem Fall erhält man $m_{00}=0$, $m_{01}=2$ und $m_{02}=-1$. Analog erhält man für die zweite Zeile der Matrix $m_{10}=-2$, $m_{11}=0$ und $m_{12}=7$ (nachrechnen!!).  
In der Abbildung sieht man zur Kontrolle die einzelnen Transformationen, aus denen die gesamte zusammengesetzt ist. Diese erhält man durch die Multiplikation der einzelnen Matrizen, aus denen die gesamte Abbildung zusammengesetzt ist.

|Verschiebung um (-4,3) |Drehung um 90°| Verschiebung um (4,-3)| Streckung um -2|
| :---: | :---: | :---: | :---: |
|$\begin{pmatrix} 1 & 0 & -4 \\ 0 & 1 & 3\\ 0 & 0 & 1 \end{pmatrix}$ |$\begin{pmatrix} 0& -1&0 \\1&0&0\\ 0 & 0 & 1 \end{pmatrix}$|$\begin{pmatrix} 1 & 0 & 4 \\ 0 & 1 & -3\\ 0 & 0 & 1 \end{pmatrix}$|$\begin{pmatrix} -2 & 0 & 0 \\ 0 & -2 & 0\\ 0 & 0 & 1 \end{pmatrix}$ |


Diese Tabelle ist von rechts nach links zu lesen, also wird das Dreieck ABC zuerst um -2 gestreckt:
$$\begin{pmatrix} -2 & 0 & 0 \\ 0 & -2 & 0\\ 0 & 0 & 1 \end{pmatrix}\cdot
\begin{pmatrix} 1 & 3 & 2 \\ 2 & 0 & 2\\ 1 & 1& 1 \end{pmatrix} =
\begin{pmatrix} -2 & -6 & -4 \\ -4 & 0 & -4\\ 1 & 1& 1 \end{pmatrix}$$

Danach erfolgt die Verschiebung, dann die Drehung und abschließend wieder die Verschiebung.  
**Auch diese Berechnungen kann man nur verstehen, wenn man nachrechnet.**
Zur Kontrolle kann man die Koordinaten der Abbildung unten entnehmen.

![Transformationen](bilder/transformationenBeispiel.png "Beispiel")