# XOR neuronales Netz zu Testen
die Gewichte werden zufällig bestimmt 

In [1]:
import numpy
import math,random

In [2]:
# Klassendefinition
class neuralNetwork:    
    # initialise the neural network
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        # set number of nodes in each input, hidden, output layer
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes
        self.trainingslaeufe=0 #zu Zählen der Durchläufe
        # Gewichtsmatrizen, wih and who       
        self.wih = numpy.random.normal(0.0, pow(20, -0.5), (self.hnodes, self.inodes))        
        self.who = numpy.random.normal(0.0, pow(20, -0.5), (self.onodes, self.hnodes))
        print("whi",self.wih)
        print("who",self.who)
        # learning rate
        self.lr = learningrate
        
        
    def activation_function(self,y_array):
        lx=len(y_array)  
        ly=len(y_array[0])
        aus=[]
        for i in range(lx):
            zeile=[]
            for j in range(ly):
                zeile.append(1/(1+math.exp(-y_array[i][j])))
            aus.append(zeile)
        aus=numpy.array(aus)
        return aus
    
    # train the neural network
    def train(self, inputs_list, targets_list):
        self.trainingslaeufe+=1
        # convert inputs list to 2d array
        inputs = numpy.array(inputs_list, ndmin=2).T
        #print("Inputs_train: \n",inputs_list,inputs)
        targets = numpy.array(targets_list, ndmin=2).T
        #print("Targets_train: \n",targets_list,targets)
        # calculate signals into hidden layer
        hidden_inputs = numpy.dot(self.wih, inputs)
        # calculate the signals emerging from hidden layer
        #print("HiddenInputs: \n",hidden_inputs)
        hidden_outputs = self.activation_function(hidden_inputs)
        #print("Hidden Outputs: \n",hidden_outputs)
        # calculate signals into final output layer
        final_inputs = numpy.dot(self.who, hidden_outputs)
        #print("FinalInputs: \n",final_inputs)
        # calculate the signals emerging from final output layer
        final_outputs = self.activation_function(final_inputs)
        #print("FINAL OUT: \n",final_outputs,"\nTargets:\n",targets)
        # output layer error is the (target - actual)
        output_errors = targets - final_outputs
        #print("Out_Errors:\n",output_errors)
        # hidden layer error is the output_errors, split by weights, recombined at hidden nodes
        hidden_errors = numpy.dot(self.who.T, output_errors) 
        #print("Hidden_Errors:\n",hidden_errors)
        # update the weights for the links between the hidden and output layers
        self.who += self.lr * numpy.dot((output_errors * final_outputs * (1.0 - final_outputs)), numpy.transpose(hidden_outputs))
        
        # update the weights for the links between the input and hidden layers
        self.wih += self.lr * numpy.dot((hidden_errors * hidden_outputs * (1.0 - hidden_outputs)), numpy.transpose(inputs))
        #print("Gewichte nach Runde:",self.trainingslaeufe,"\n",self.wih,"\n",self.who)
        pass

    
    # query the neural network
    def query(self, inputs_list):
        # convert inputs list to 2d array
        inputs = numpy.array(inputs_list, ndmin=2).T
        #print("Inputs",inputs)
        # calculate signals into hidden layer
        hidden_inputs = numpy.dot(self.wih, inputs)
        #print("hidden",hidden_inputs)
        # calculate the signals emerging from hidden layer
        hidden_outputs = self.activation_function(hidden_inputs)
        
        # calculate signals into final output layer
        final_inputs = numpy.dot(self.who, hidden_outputs)
        #print("final_in",final_inputs)
        # calculate the signals emerging from final output layer
        final_outputs = self.activation_function(final_inputs)
        
        return final_outputs
    def test(self,eingabe):
        
        aus=self.query(eingabe)
        text="Eingaben: "
        for e in eingabe:
            text+=str(e)
            text+=", "
        #print(text)
        austext="  Ausgaben: "
        for a in aus:
            austext+=str(a[0])
            austext+=", "
        print(text+austext)

In [3]:
# number of input, hidden and output nodes
input_nodes = 2
hidden_nodes = 5
output_nodes = 2

# learning rate is 0.3
learning_rate = 0.5

# create instance of neural network
n = neuralNetwork(input_nodes,hidden_nodes,output_nodes, learning_rate)
trainingsDaten=[[0.01,0.99,0.99,0.01],[0.01,0.01,0.01,0.99],[0.99,0.01,0.99,0.01],[0.99,0.99,0.01,0.99]]*1000

for liste in trainingsDaten:
    inListe=numpy.array(liste[:2])
    tarListe=numpy.array(liste[-2:])    
    n.train(inListe,tarListe) #Training 
n.test([0,0])
n.test([0,1])
n.test([1,0])
n.test([1,1])
print("Anzahl der Trainingsläufe ",n.trainingslaeufe)
print("Gewichte am Ende")
print(n.wih)
print(n.who)

whi [[ 0.04639992 -0.0419245 ]
 [-0.10562281 -0.50489415]
 [ 0.07076619  0.21561176]
 [-0.0703029  -0.01155009]
 [ 0.01221917 -0.11663126]]
who [[-0.09144007  0.05702747  0.17782002  0.13697548  0.06016449]
 [-0.25848211 -0.41446644  0.19614108 -0.14934352  0.10012611]]
Eingaben: 0, 0,   Ausgaben: 0.14412266957428677, 0.8551858764435755, 
Eingaben: 0, 1,   Ausgaben: 0.8402675334150765, 0.1577128786325738, 
Eingaben: 1, 0,   Ausgaben: 0.8920074965518823, 0.10706201341083177, 
Eingaben: 1, 1,   Ausgaben: 0.14820915178922117, 0.8564784693641185, 
Anzahl der Trainingsläufe  4000
Gewichte am Ende
[[-2.8884134   0.69791887]
 [ 3.88524129 -8.76826823]
 [-1.55829759  4.07573625]
 [-8.89977235  4.16285637]
 [-5.76849936 -5.93821016]]
[[ 0.04938776  2.52241098 -1.9495613   3.61985953 -7.80502147]
 [-0.31940393 -2.53037845  2.01872076 -3.52144372  7.90424101]]
