# Probenetz zum Durchrechnen per Hand

Quelle: Tariq Rashid  Frank Langenau (Übersetzung) Neuronale Netze selbst programmieren O’Reilly:  
https://www.oreilly.de/buecher/12892/9783960090434-neuronale-netze-selbst-programmieren.html  
Die Gewichte sind fest vorgegeben, um nachvollziehbare Ergebnisse zu bekommen.

In [1]:
import numpy
import math,random

In [25]:
# Klassendefinition
class neuralNetwork:    
    # initialise the neural network
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        # Anzahl der Knoten in jeder Schicht: input, hidden, output layer
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes      
        self.wih =numpy.array([[0.2,0.3],[0.4,0.3],[0.1,0.4]])# Gewichte W IH
        self.who =numpy.array([[0.2,0.3,0.4],[0.1,0.2,0.6]]) # Gewichte W HO
        print("whi",self.wih)
        print("who",self.who)
        self.lr=learningrate
       
        
    def activation_function(self,y_array):
        # wendet auf jedem Element eines Vektors die Sigmoid-Funktion an
        # und liefert einen Vektor zurück
        lx=len(y_array)  
        ly=len(y_array[0])
        aus=[]
        for i in range(lx):
            zeile=[]
            for j in range(ly):
                zeile.append(round(1/(1+math.exp(-y_array[i][j])),3))
            aus.append(zeile)
        aus=numpy.array(aus)
        return aus
    
    # train the neural network
    def train(self, inputs_list, targets_list):        
        # convert inputs list to 2d array
        inputs = numpy.array(inputs_list, ndmin=2).T
        #print("Inputs_train: \n",inputs_list,inputs)
        targets = numpy.array(targets_list, ndmin=2).T
        #print("Targets_train: \n",targets_list,targets)
        # calculate signals into hidden layer
        hidden_inputs = numpy.dot(self.wih, inputs)
        # calculate the signals emerging from hidden layer
        print("HiddenInputs: \n",hidden_inputs)
        hidden_outputs = self.activation_function(hidden_inputs)
        print("Hidden Outputs: \n",hidden_outputs)
        # calculate signals into final output layer
        final_inputs = numpy.dot(self.who, hidden_outputs)
        print("FinalInputs: \n",final_inputs)
        # calculate the signals emerging from final output layer
        final_outputs = self.activation_function(final_inputs)
        print("FINAL OUT: \n",final_outputs,"\nTargets:\n",targets)
        # output layer error is the (target - actual)
        output_errors = targets - final_outputs
        print("Out_Errors:\n",output_errors)
        # hidden layer error is the output_errors, split by weights, recombined at hidden nodes
        hidden_errors = numpy.dot(self.who.T, output_errors) 
        print("Hidden_Errors:\n",hidden_errors)
        # update the weights for the links between the hidden and output layers
        self.who += self.lr * numpy.dot((output_errors * final_outputs * (1.0 - final_outputs)), numpy.transpose(hidden_outputs))
        # update the weights for the links between the input and hidden layers
        self.wih += self.lr * numpy.dot((hidden_errors * hidden_outputs * (1.0 - hidden_outputs)), numpy.transpose(inputs))
        print("korrigierte Gewichte who:\n",self.who)
        print("korrigierte Gewichte wih:\n",self.wih)
        
        
    # zum Testen nach dem Training
    def query(self, inputs_list):
        # convert inputs list to 2d array
        inputs = numpy.array(inputs_list, ndmin=2).T
        #print("Inputs",inputs)
        # calculate signals into hidden layer
        hidden_inputs = numpy.dot(self.wih, inputs)
        #print("hidden",hidden_inputs)
        # calculate the signals emerging from hidden layer
        hidden_outputs = self.activation_function(hidden_inputs)
        
        # calculate signals into final output layer
        final_inputs = numpy.dot(self.who, hidden_outputs)
        #print("final_in",final_inputs)
        # calculate the signals emerging from final output layer
        final_outputs = self.activation_function(final_inputs)        
        return final_outputs
    
    def test(self,eingabe):        
        aus=self.query(eingabe)
        text="Eingaben: "
        for e in eingabe:
            text+=str(e)
            text+=", "
        #print(text)
        austext="  Ausgaben: "
        for a in aus:
            austext+=str(a[0])
            austext+=", "
        print(text+austext)

### Training des Netzes (eine Runde)

In [26]:
# number of input, hidden and output nodes
input_nodes = 2
hidden_nodes = 3
output_nodes = 2

# learning rate is 0.3
learning_rate = 0.5

# create instance of neural network
n = neuralNetwork(input_nodes,hidden_nodes,output_nodes, learning_rate)
trainingsDaten=[[0,1,1,0]]#,[1,0,1,0],[0,1,1,0],[1,1,0,1]]
#trainingsDaten=[[0,1,1,0],[1,0,1,0],[0,1,1,0],[1,1,0,1]]
for liste in trainingsDaten:
    inListe  = numpy.array(liste[:2])
    tarListe = numpy.array(liste[-2:])
    print("Eingabe:\n",inListe)
    print("Targets:\n",  tarListe)
    n.train(inListe,tarListe) #Training 


whi [[0.2 0.3]
 [0.4 0.3]
 [0.1 0.4]]
who [[0.2 0.3 0.4]
 [0.1 0.2 0.6]]
Eingabe:
 [0 1]
Targets:
 [1 0]
HiddenInputs: 
 [[0.3]
 [0.3]
 [0.4]]
Hidden Outputs: 
 [[0.574]
 [0.574]
 [0.599]]
FinalInputs: 
 [[0.5266]
 [0.5316]]
FINAL OUT: 
 [[0.629]
 [0.63 ]] 
Targets:
 [[1]
 [0]]
Out_Errors:
 [[ 0.371]
 [-0.63 ]]
Hidden_Errors:
 [[ 0.0112]
 [-0.0147]
 [-0.2296]]
korrigierte Gewichte who:
 [[0.22484737 0.32484737 0.42592957]
 [0.05785319 0.15785319 0.55601753]]
korrigierte Gewichte wih:
 [[0.2        0.30136933]
 [0.4        0.29820275]
 [0.1        0.37242515]]


### Test des (trainierten) Netzes

In [22]:
n.test([0,0])
n.test([0,1])
n.test([1,0])
n.test([1,1])
print("Gewichte am Ende")
print(n.wih)
print(n.who)

Eingaben: 0, 0,   Ausgaben: 0.62, 0.595, 
Eingaben: 0, 1,   Ausgaben: 0.638, 0.611, 
Eingaben: 1, 0,   Ausgaben: 0.632, 0.603, 
Eingaben: 1, 1,   Ausgaben: 0.65, 0.619, 
Gewichte am Ende
[[0.2        0.30136933]
 [0.4        0.29820275]
 [0.1        0.37242515]]
[[0.22484737 0.32484737 0.42592957]
 [0.05785319 0.15785319 0.55601753]]
