In [6]:
import numpy as np
def sigmoid(x, deriv = False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))
np.random.seed(1)
X = np.array([[1, 0, 0],[1, 0, 1],[1, 1, 0],[1, 1, 1]])#x0 ist BIAS 
X0=X.reshape(4,1,3)    #damit die einzelnen Eingaben als Matrix und nicht als Vektor behandelt werden!!
y = np.array([[0,1], [1,0], [1,0], [0,1]])
#Anzahl der Neuronen
anz_In=2
anz_H=3
anz_Out=2
wIH=np.ones((anz_In+1,anz_H),float)/10
wIH[0][1]=0.2
print("wHI\n",wIH)
wHO=np.ones((anz_H,anz_Out),float)/10
wHO[0][0]=0.2  #etwas Asymmetrie
print("wHO\n",wHO)
syn0=wIH#np.array([[0.1,0.1,0.1],[0.1,0.1,0.1],[0.1,0.1,0.1]])
syn1=wHO#np.array([[0.2],[0.1],[0.1]])
#print(syn0)
#print(syn1)
#For loop iterate over the training set
debug= False
a=np.array([0,1,2,3])
for i in range(2000):    
    np.random.shuffle(a)
    for j in a:        
        l0 = X0[j]
        if debug:  print("l0\n",l0)
        l1 = (np.dot(l0, syn0)) 
        if debug:  print("l1\n",l1)
        l1=sigmoid(l1)
        l2 = (np.dot(l1,syn1))
        if debug:  print("l2\n",l2)
        l2=sigmoid(l2)
        l2_error = y[j] - l2
        if debug:  print("Fehler\n",l2_error)
        l2_delta = l2_error*sigmoid(l2, deriv=True)  
        if debug:  print("l2_delta\n",l2_delta)
        l1_error = l2_delta.dot(syn1.T)
        if debug:  print("l1_error\n",l1_error)
        l1_delta = l1_error * sigmoid(l1, deriv=True)  
        if debug:  print("l1_delta\n",l1_delta)
        syn1_korr=np.dot(l1.T,l2_delta)
        if debug:  print("syn1_korr\n",syn1_korr)
        syn1 += syn1_korr        
        syn0_korr=np.dot(l0.T,l1_delta)
        syn0 += syn0_korr
        if debug:  print("syn0_korr\n",syn0_korr)
        
l1 = sigmoid(np.dot(X, syn0))    
l2 = sigmoid(np.dot(l1,syn1))
l2_error = y - l2
print("Ausgabe\n",l2)
print("Fehler\n",l2_error)
print("Gewichte IH\n",syn0)
print("Gewichte HO\n",syn1)

wHI
 [[0.1 0.2 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]
wHO
 [[0.2 0.1]
 [0.1 0.1]
 [0.1 0.1]]
Ausgabe
 [[0.03118303 0.96880992]
 [0.96589586 0.03411517]
 [0.9658065  0.03420454]
 [0.04525685 0.95472355]]
Fehler
 [[-0.03118303  0.03119008]
 [ 0.03410414 -0.03411517]
 [ 0.0341935  -0.03420454]
 [-0.04525685  0.04527645]]
Gewichte IH
 [[ 8.36777081  2.84981823  1.04508887]
 [-5.66428716 -7.05616581  0.80274339]
 [-5.66849882 -7.05669617  0.79250439]]
Gewichte HO
 [[ 7.0457153  -7.04485735]
 [-8.24049428  8.23975572]
 [-3.63659593  3.63606484]]
