# Netz zum Lernen von XOR
## Initialisierung
2 Eingaben und BIAS, 5 Neuronen in der Hidden Schicht und ein Ausgabeneuron
<img src="bilder/netzarchitektur.png"  width="360">

In [30]:
import numpy as np
def sigmoid(x, deriv = False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

X = np.array([[0, 0, 1],[0, 1, 1],[1, 0, 1],[1, 1, 1]])
y = np.array([[0], [1], [1], [0]   ])
nr=0
wIH = np.ones((len(X[0]), 5)) #eine Eingabe aus den vieren 
print("Gewichte:\n",wIH)
wHO = np.ones((5, 1))
HI=np.dot(X,wIH)
print("HiddenIn: \n",HI)
H_act =sigmoid(-HI)
print("Hidden act:\n",H_act)

Gewichte:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
HiddenIn: 
 [[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]]
Hidden act:
 [[0.26894142 0.26894142 0.26894142 0.26894142 0.26894142]
 [0.11920292 0.11920292 0.11920292 0.11920292 0.11920292]
 [0.11920292 0.11920292 0.11920292 0.11920292 0.11920292]
 [0.04742587 0.04742587 0.04742587 0.04742587 0.04742587]]


In [31]:
O_In=np.dot(H_act,wHO)
print("OutIn:\n",O_In)
O_act=sigmoid(-O_In)
print("OutAct:\n",O_act)
O_error = ((1 / 2) * (np.power((O_act - y), 2)))
print("Fehler Out:\n",O_error)


OutIn:
 [[1.34470711]
 [0.59601461]
 [0.59601461]
 [0.23712937]]
OutAct:
 [[0.20673704]
 [0.35525602]
 [0.35525602]
 [0.44099389]]
Fehler Out:
 [[0.0213701 ]
 [0.2078474 ]
 [0.2078474 ]
 [0.09723781]]


## Backpropagation
Aus dem Fehler wird die Korrektur der Gewichte berechnet.

https://towardsdatascience.com/understanding-neural-networks-what-how-and-why-18ec703ebd31

In [33]:
import numpy as np
def sigmoid(x, deriv = False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

X = np.array([[0, 0, 1],[0, 1, 1],[1, 0, 1],[1, 1, 1]])
y = np.array([[0], [1], [1], [0]   ])
anz_H=2
syn0 = 2+np.random.random((3,anz_H)) -1
syn1 = 2+np.random.random((anz_H,1)) -1
print(syn0)
print(syn1)

#For loop iterate over the training set
for i in range(4000):    
    #First layer is the input    
    l0 = X    
    #Second layer can be obtained with the multiplication of each layer 
    #and its synapsis and then running sigmoid function 
    l1 = sigmoid(np.dot(l0, syn0))    
    #Do the same with l1 and its synapsis 
    l2 = sigmoid(np.dot(l1,syn1))
        #Compute the error by checking how far the prediction 
    #is from the real value.
    l2_error = y - l2
    #multiply error rate by result of sigmoide on l2 to get derivative
    #from output
    #Delta will be use to reduce error rate of prediction when update syn     
    #FORMULA 1
    l2_delta = l2_error*sigmoid(l2, deriv=True)    
    #How much l1 contributed to error in l2. Multiply
    #layer2_delta with syn1 transpose. 
    l1_error = l2_delta.dot(syn1.T)    
    #get delta for l1 
    l1_delta = l1_error * sigmoid(l1, deriv=True)    
    #Update our synapse rates to reduce the error rate every iteration
    #Multiply each layer by a delta    
    #*BACKPROPAGATION*
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
    
    if i%1000==0:
        print(syn0)
        print(syn1)
l1 = sigmoid(np.dot(l0, syn0))    
#Do the same with l1 and its synapsis 
l2 = sigmoid(np.dot(l1,syn1))
#Compute the error by checking how far the prediction 
#is from the real value.
l2_error = y - l2
print(l2)


[[1.01681234 1.72407211]
 [1.81226166 1.1929248 ]
 [1.41207495 1.98180837]]
[[1.52486824]
 [1.24188552]]
[[1.01616019 1.72370856]
 [1.8113412  1.19262652]
 [1.39379673 1.97181179]]
[[1.4200206 ]
 [1.13135636]]
[[0.99728133 1.71578551]
 [1.78312107 1.17650885]
 [1.41013513 1.88850854]]
[[ 0.03079097]
 [-0.0879398 ]]
[[0.98572408 1.71914947]
 [1.77056686 1.17588081]
 [1.45894448 1.84850981]]
[[ 0.06648722]
 [-0.05241984]]
[[0.9349293  1.72763422]
 [1.77658049 1.16743672]
 [1.42235812 1.8507843 ]]
[[ 0.22419176]
 [-0.20142168]]
[[0.49563247]
 [0.49387306]
 [0.49252539]
 [0.49708699]]
