In [2]:
import numpy as np
dreieck = np.array([[2,3],[3,1],[7,1]],"int")
def homogenisiere(figur):
    #macht aus der Liste der Koordinaten eine homogene Matrix
    m=np.full((3,figur.shape[0]),1,'int')
    m[:2,:]=np.transpose(figur)#
    return m
d=homogenisiere(dreieck)
d

array([[2, 3, 7],
       [3, 1, 1],
       [1, 1, 1]])

In [5]:
m = np.array([[0,-2,5],[2,0,-1],[0,0,1]])
m1=np.dot(m,d)
m1

array([[-1,  3,  3],
       [ 3,  5, 13],
       [ 1,  1,  1]])

In [9]:
inv=np.linalg.inv(m)
inv

array([[ 0. ,  0.5,  0.5],
       [-0.5, -0. ,  2.5],
       [ 0. ,  0. ,  1. ]])

In [8]:
m2 = np.dot(inv,m1)
m2


array([[2., 3., 7.],
       [3., 1., 1.],
       [1., 1., 1.]])