# Eigene Implementation eines K-Nearest-Neighbor Algorithmus

Ziel:
* Entwicklung eines eigenen KNN Algorithmus
* möglichst gute Performance --> wenige Schlaufen-Iterationen --> O(n) Laufzeit
* Kompatibilität mit Scikit Features

In [3]:
import numpy as np
import numpy.linalg as nl
from collections import Counter

## Create a SciKit compatible Class of MyKNN
In order to use all the nice features of scikit like cross_val_score and GridSearchCV, etc. let's see if we can subklass from SciKit Estimators and create our own MyKNN Classifier

In [4]:
from sklearn.base import BaseEstimator, ClassifierMixin

class MyKNN(BaseEstimator, ClassifierMixin):  
    """An example of a KNN classifier, compatible with scikit-learn"""
    
    def __init__(self, n_neighbors=5, debug=False):
        """
        Called when initializing the classifier
        Default kNeighbors Value is 5
        """
        self.n_neighbors = n_neighbors
        self.debug = debug
        
    def fit(self, X, y=None):
        """
        This should fit classifier. 
        
        Since in KNN the Algorigthm needs no training,
        we just assign X and y values.
        """
        self.X = X
        self.y = y
        
        if (len(self.X) < self.n_neighbors):
            print("Initialized n_neighbors is larger than available samples in X.")
            print("Setting n_neighbors to length of samples: {}".format(len(self.X)))
            self.n_neighbors = len(self.X)
        
        return self
    
    def predict(self, X, y=None):
        try:
            getattr(self, "X")
        except AttributeError:
            raise RuntimeError("You must train classifer before predicting data!")
    
        # prepare result vector
        self.classindexes = []
        for i in X:
            dist = nl.norm(np.transpose(i-self.X), axis=0)        
            self.classindexes.append(Counter(self.y[np.argsort(dist)[:self.n_neighbors]]).most_common(1)[0][0])
            if (self.debug):
                print("current i:")
                print(i)
                print("current dist:")
                print(dist)
                print("indexes of sorted shorted distances:")
                print(np.argsort(dist))
                print("k nearest indexes:")
                print(np.argsort(dist)[:self.n_neighbors])
                print("classes of these k nearest indexes:")
                print(self.y[np.argsort(dist)[:self.n_neighbors]])
                print("most common class:")
                print(Counter(self.y[np.argsort(dist)[:self.n_neighbors]]).most_common(1)[0][0])
        return(self.classindexes)

## Create some test classes

In [42]:
Xb = np.array([[1, 1, 1.2, 3.7, 6.1, 9.8, 7, 10, 11.8, 16.4], [8.8, 11, 15.9, 11, 8.8, 14.5, 17, 8.1, 17.5, 15.8]])
y = np.array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0])

In [70]:
Xb = np.array([[1, 8.8], [1, 11], [1.2, 15.9], [3.7, 11], [6.1, 8.8], [9.8, 14.5], [7, 17], [10, 8.1], [11.8, 17.5], [16.4, 15.8], [11,10]])

In [71]:
y = np.array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [68]:
y

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0])

In [43]:
Xu = np.array([[9, 5], [9, 5]])

In [56]:
Xb.shape

(10, 2)

In [64]:
Xb

array([[  1. ,   8.8],
       [  1. ,  11. ],
       [  1.2,  15.9],
       [  3.7,  11. ],
       [  6.1,   8.8],
       [  9.8,  14.5],
       [  7. ,  17. ],
       [ 10. ,   8.1],
       [ 11.8,  17.5],
       [ 16.4,  15.8]])

In [65]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [45]:
y.shape

(10,)

In [72]:
test = MyKNN()

In [73]:
clf = MyKNN(n_neighbors=3, debug=False)

In [74]:
clf2 = MyKNN(n_neighbors=5, debug=True)

In [59]:
# predict some iris data
from sklearn import datasets
iris = datasets.load_iris()
iris.data.shape
X = iris.data[:, :]
y= iris.target

In [60]:
iris.data.shape

(150, 4)

In [61]:
X.shape

(150, 4)

In [62]:
y.shape

(150,)

In [63]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
X

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [75]:
# test should be initialized with default values from _init_
test.fit(Xb, y)

MyKNN(debug=False, n_neighbors=5)

In [76]:
clf.fit(Xb, y)

MyKNN(debug=False, n_neighbors=3)

In [77]:
clf2.fit(Xb, y)

MyKNN(debug=True, n_neighbors=5)

## Test predictions 
Let's do some first predictions with clf and clf2

In [79]:
Xu = np.array([[9, 9],[5, 5]])

In [80]:
clf2.predict(Xu)

current i:
[9 9]
current dist:
[  8.00249961   8.24621125  10.41393297   5.66480362   2.90688837
   5.55787729   8.24621125   1.3453624    8.94930165  10.04987562
   2.23606798]
indexes of sorted shorted distances:
[ 7 10  4  5  3  0  1  6  8  9  2]
k nearest indexes:
[ 7 10  4  5  3]
classes of these k nearest indexes:
[0 0 1 1 1]
most common class:
1
current i:
[5 5]
current dist:
[  5.51724569   7.21110255  11.54339638   6.13921819   3.95600809
  10.64377752  12.16552506   5.88302643  14.2298981   15.70350279
   7.81024968]
indexes of sorted shorted distances:
[ 4  0  7  3  1 10  5  2  6  8  9]
k nearest indexes:
[4 0 7 3 1]
classes of these k nearest indexes:
[1 1 0 1 1]
most common class:
1


[1, 1]

In [81]:
clf.predict(Xu)

[0, 1]

In [10]:
new_iris_values = np.array([[3, 5, 4, 2], [5, 4, 3, 2]])

In [11]:
meine_iris_values = np.array([[3.0, 4.9, 3.8, 2.2], [6.0,  3.6,  5.2,  2.4]])

In [40]:
clf.predict(new_iris_values)

NameError: name 'new_iris_values' is not defined

In [13]:
clf.predict(meine_iris_values)

[1, 2]

In [16]:
clf2.predict(meine_iris_values)

current i:
[ 3.   4.9  3.8  2.2]
current dist:
[ 4.01621713  4.12067956  4.00374824  3.88458492  3.9306488   3.79605058
  3.76563408  3.94208067  3.96484552  4.06816912  4.0607881   3.78549865
  4.12553027  4.12310563  4.40567815  4.00874045  4.03112887  3.96736688
  4.06448029  3.81051178  4.05215992  3.79209705  4.01123422  3.77756535
  3.61939221  4.05585996  3.78549865  4.01123422  4.10487515  3.82361086
  3.91407716  4.06693988  3.89615195  4.0620192   4.06816912  4.20119031
  4.29651021  4.06816912  3.97743636  3.99374511  3.97743636  4.34396133
  3.88587185  3.65513338  3.53128872  4.02740611  3.80263067  3.9
  4.00249922  4.03980198  4.50998891  3.92810387  4.48887514  3.72290209
  4.21781934  3.60555128  3.82361086  3.39852909  4.29068759  3.21403174
  3.73363094  3.55949435  4.21544778  3.88072158  3.40734501  4.23438307
  3.36897611  3.76961536  4.30232495  3.7067506   3.52987252  3.8561639
  4.28369     3.97869325  4.07676342  4.19165838  4.52658812  4.35775171
  3.73898382

[1, 2]

In [12]:
clf2.predict(new_iris_values)

current i:
[3 5 4 2]
current dist:
[ 4.08166633  4.19642705  4.08166633  3.95727179  3.99499687  3.84967531
  3.84317577  4.00624512  4.04598566  4.13279566  4.11582313  3.84707681
  4.19642705  4.20832508  4.46318272  4.05709256  4.10121933  4.0385641
  4.11217704  3.87169214  4.10487515  3.86134692  4.0938979   3.85227206
  3.66742416  4.12310563  3.8574603   4.07185461  4.17133072  3.88973007
  3.98120585  4.13884042  3.93827373  4.10974452  4.13279566  4.28018691
  4.36233882  4.13279566  4.0607881   4.05709256  4.05339364  4.44072066
  3.9661064   3.73764632  3.58050276  4.10974452  3.85356977  3.97492138
  4.05832478  4.10974452  4.48218697  3.91152144  4.45869936  3.74566416
  4.20713679  3.58747822  3.79868398  3.44383507  4.26848919  3.24037035
  3.77491722  3.56370594  4.22374242  3.8561639   3.43802269  4.22137418
  3.35559235  3.76031914  4.31045241  3.7188708   3.51140997  3.86522962
  4.2661458   3.94715087  4.06816912  4.18090899  4.5033321   4.33358974
  3.72961124  3.7

[1, 1]

# Testing SciKit Features

##  train_test_split

In [13]:
# compute classification accuracy for MyKNN implementation
# split X and y into training and testing sets
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn import metrics, model_selection
from sklearn.neighbors import KNeighborsClassifier
# import RandomForest & GradientBoost
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
import pandas as pd

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=4)

In [14]:
# predict using MyKNN
clf = MyKNN(n_neighbors=5)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

# compare actual response values (y_test) with predicted response values (y_pred)
print(metrics.accuracy_score(y_test, y_pred))

0.966666666667


## GridSearchCV

In [15]:
# define the parameter values that should be searched
k_range = list(range(1, 31))
# create a parameter grid: map the parameter names to the values that should be searched
param_grid = dict(n_neighbors=k_range)
# instantiate the grid
grid = model_selection.GridSearchCV(MyKNN(), param_grid, cv=10, scoring='accuracy')
# fit the grid with data
grid.fit(X, y)
# examine the best model
print(grid.best_score_)
print(grid.best_params_)
print(grid.best_estimator_)

0.98
{'n_neighbors': 13}
MyKNN(debug=False, n_neighbors=13)


# Comparison with other SciKit classifiers

In [16]:
classifiers = {
    "MyKNN": MyKNN(13),
    "SciKit-KNN": KNeighborsClassifier(13),
    "Gradient Boosting Classifier": GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=0),
    "Random Forest": RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1)
}

In [17]:
# iterate over classifiers
# calculate accuracy
results = []
for key, clf in classifiers.items():
    print("training clf: {}".format(key))
    scores = model_selection.cross_val_score(clf, X, y, cv=5, scoring='accuracy', n_jobs=4)
    results.append([key, scores.mean(), scores.std()])
df_results = pd.DataFrame(data=results, columns=['clf_name', 'mean_score', 'std'])
print(df_results)

training clf: MyKNN
training clf: SciKit-KNN
training clf: Gradient Boosting Classifier
training clf: Random Forest
                       clf_name  mean_score       std
0                         MyKNN    0.973333  0.024944
1                    SciKit-KNN    0.973333  0.024944
2  Gradient Boosting Classifier    0.960000  0.024944
3                 Random Forest    0.960000  0.024944
