In [1]:
meineListe = [2.1, 0 , 3.1]

In [2]:
print(meineListe)

[2.1, 0, 3.1]


In [3]:
meineListe.append(-5)

In [4]:
print(meineListe)

[2.1, 0, 3.1, -5]


In [7]:
import numpy as np

In [8]:
meineListe = [10, 120, 250, 50, 88, 99, 600]

In [9]:
meinArray = np.array(meineListe)

In [10]:
print(meinArray)

[ 10 120 250  50  88  99 600]


In [11]:
print(meinArray * 0.621371)

[   6.21371    74.56452   155.34275    31.06855    54.680648   61.515729
  372.8226  ]


In [12]:
meinArrayInMeilen = meinArray * 0.621371

In [13]:
type(meinArrayInMeilen)

numpy.ndarray

In [15]:
A = np.array([ [ 2.1, 0, 6.21, 2.1], [-3.5, 3.45, 9.2, 1.55], [22, 0.45, 3.14, -32.1]])

In [16]:
print(A)

[[  2.1    0.     6.21   2.1 ]
 [ -3.5    3.45   9.2    1.55]
 [ 22.     0.45   3.14 -32.1 ]]


In [18]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [22]:
B= np.ones((3,4))

In [23]:
B

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [24]:
A

array([[  2.1 ,   0.  ,   6.21,   2.1 ],
       [ -3.5 ,   3.45,   9.2 ,   1.55],
       [ 22.  ,   0.45,   3.14, -32.1 ]])

In [25]:
C=A-B

In [26]:
print(C)

[[  1.1   -1.     5.21   1.1 ]
 [ -4.5    2.45   8.2    0.55]
 [ 21.    -0.55   2.14 -33.1 ]]


In [27]:
print(A.T)

[[  2.1   -3.5   22.  ]
 [  0.     3.45   0.45]
 [  6.21   9.2    3.14]
 [  2.1    1.55 -32.1 ]]


In [31]:
Czufall = np.random.random((4,3))*3

In [32]:
Czufall

array([[ 1.84478961,  1.39724572,  2.36192324],
       [ 2.70629182,  1.92522659,  0.19286645],
       [ 1.39837424,  0.96424332,  2.08155174],
       [ 2.60238061,  2.01473856,  0.66614434]])

In [33]:
print(np.matmul(A,Czufall))

[[ 18.02296147  13.15311799  19.28537819]
 [ 19.77867607  13.74555499  12.58145763]
 [-37.34231983 -30.03962606  37.20194038]]


In [34]:
print(np.matmul(A,Czufall.T))

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)